### PR TITLE
Allow to set PHP values per pool; refactor and document role

### PR DESCRIPTION
**Pull request by SlothOfAnarchy**

### CODE REVIEW

**Review by haslersn — CHANGES_REQUESTED** [review]
I suggest merging this commit: https://github.com/stuvusIT/php-fpm/commit/2abab838fb5350b28fd709ca9078fe788f30c5f9

**Comment by SlothOfAnarchy** [comment]
@haslersn done

**Comment by SlothOfAnarchy** [comment]
fixes #39

**Comment by haslersn** [comment]
Closes #39

**Review by haslersn — APPROVED** [review]

**Pull request merged**
